---
title: "Variables nécessitant des précisions"
author: "CLESSN"
date: "2022-11-30"
output: pdf_document
---
# Liste des codes à lettres/chiffres et leur signification 

UL_ACAD_ORG_01

- Il faudrait pouvoir associer les codes de faculté à 3 lettres aux noms complets des facultés.


UL_MAJOR1_CD_01

- Il faudrait pouvoir associer les codes de programme aux noms complets des programmes.


UL_EDUCATIO_LVL_PI

- Nous avons besoin d'explications sur les codes du niveau d’étude le plus important (de 51 à 59). 


UL_GRP_EMPL_FUL et UL_GR_EMPLOI_RH

- Nous avons besoin d'explications sur les codes d’emploi FUL et RH (à 4 chiffres).


UL_TYPE_EMPLOI

- Nous avons besoin d'explications sur les codes "types d’emplois UL" (N et R).


UL_TYP_COL_FUL_CD

- Nous avons besoin d'explications sur les codes des types de collaborateur FUL (1 2 3 5 50 51 6 7 9)


UL_RSLT_D_A_SOL

- Besoin de savoir la signification des valeurs de la variable


# Définitions
Nous avons besoin des définitions des termes et expressions suivantes:

- Promesses ouvertes
    - Montant attendu
    - Promesse illimitée
    
- Indicateur de service négatif




